name: CI/CD to EC2 with Tomcat

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build WAR
        run: ./gradlew clean build -x test

      - name: Upload WAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST_THEPAIN }}
          username: ${{ secrets.EC2_USER_THEPAIN }}
          key: ${{ secrets.EC2_SSH_KEY_THEPAIN }}
          source: build/libs/thepain-0.0.1-SNAPSHOT.war
          target: /home/ubuntu/build

      - name: Run deploy script
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST_THEPAIN }}
          username: ${{ secrets.EC2_USER_THEPAIN }}
          key: ${{ secrets.EC2_SSH_KEY_THEPAIN }}
          script: |
            bash ~/deploy-war.sh
